apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-restore-job
spec:
  template:
    spec:
      containers:
      - name: restore
        image: mysql:8.0
        command:
        - /bin/sh
        - -c
        - |
          mysql -h mysql-service -u root -pcentos unnati < /backup/unnati.sql && echo "Restore completed"
        volumeMounts:
        - name: backup-storage
          mountPath: /backup
      restartPolicy: OnFailure
      volumes:
      - name: backup-storage
        hostPath:
          path: /opt/mysql-backups
          type: DirectoryOrCreate
